title: BroadAI
description: BroadAI is a multi-agent AI system (MAS) development framework.
google_analytics: G-NLHD8SK1HK
theme: jekyll-theme-architect

# -- For App Store
agents:
  - agent-name: "GeneralAssistant"
    package-name: "GeneralAssistant"
    capability: "This is an in-built agent. You do not have to explicitly import it in your BroadAI MAS application. It performs a variety of general, everyday tasks"
    skills:
      - skill-name: "getCurrentTime"
        objective: "Identify the appropriate Timezone area for a given location and tell time at that location"
        action: "getCurrentTime"
        parameters:
          area_location: "string | An example of area_location is America/New_York or Europe/London. Based on the valid location provided, determine appropriate area_location"
      - skill-name: "extractSpecificValue"
        objective: "Extract specific values from the provided source"
        action: "extractSpecificValue"
        parameters:
          source: "string | information source"
          question: "string | frame a question to specify which value must be extracted"
      - skill-name: "extractList"
        objective: "Extract list of requested items from the source"
        action: "extractList"
        parameters:
          source: "string | information source"
          item_category: "string | frame a question to specify which category of items must be extracted"
    agent-config: {}
  - agent-name: "Researcher"
    package-name: "Researcher"
    capability: "Looks up information using external information providers"
    skills:
      - skill-name: "researchTopic"
        objective: "Search internet for information about the given topic"
        action: "researchTopic"
        parameters:
          topic: "string | topic that must be researched"
      - skill-name: "findBusinesses"
        objective: "Search specific business type around a 10 mile radius of a given location"
        action: "findBusinesses"
        parameters:
          term: "string | business type, e.g. diner, coffee, tailor, etc."
          location: "string | address or landmark within a city and state"
      - skill-name: "readWebPage"
        objective: "Read the contents of a given web page"
        action: "readWebPage"
        parameters:
          url: "string | web page address"
    agent-config: 
      google_search_engine: 
        api_key: "?"
        programmable_search_engine_id: "?"
      yelp: 
        api_key: "?"
  - agent-name: "Aviator"
    package-name: "Aviator"
    capability: "Aviator can find the status of a specific flight number or for multiple flights between two airports"
    skills:
      - skill-name: "departingFlights"
        objective: "Retreive flights departing from specified airport"
        action: "departingFlights"
        parameters:
          iata_departure: "string | must be an IATA airport code from where flight originates, e.g. CMH for Port Columbus International Airport"
      - skill-name: "arrivingFlights"
        objective: "Retreive flights arriving into specified airport"
        action: "arrivingFlights"
        parameters:
          iata_arrival: "string | must be an IATA airport code from where flight lands, e.g. CMH for Port Columbus International Airport"
      - skill-name: "specificFlight"
        objective: "Retrieve flight details about a specific flight"
        action: "specificFlight"
        parameters:
          iata_flight_number: "string | must be an IATA flight number, e.g. IATA flight number for flight 'United 5532' is 'UA5532'"
    agent-config: 
      aviationstack: 
        api_key: "?"
  - agent-name: "Weatherman"
    package-name: "Weatherman"
    capability: "Reports current weather conditions as well as forecast"
    skills:
      - skill-name: "currentWeather"
        objective: "Obtain current weather conditions for a location"
        action: "currentWeather"
        parameters:
          city: "string | valid and recognizable City name without State or State Code. e.g. Columbus"
      - skill-name: "weatherForecast"
        objective: "Get weather forecast for a location"
        action: "weatherForecast"
        parameters:
          city: "string | valid and recognizable City name without State or State Code. e.g. Columbus"
    agent-config: 
      openweathermap: 
        api_key: "?"
  - agent-name: "NewsReporter"
    package-name: "NewsReporter"
    capability: "Report top news headlines in specific categories from specific countries"
    skills:
      - skill-name: "getHeadlines"
        objective: "Retrieve top news headlines for the specified country and specified category"
        action: "getHeadlines"
        parameters:
          country_code: "string | 2-letter country code based on ISO 3166, e.g. US for USA, IN for India, etc. | default=us"
          category: "pick only one amongst - business|entertainment|general|health|science|sports|technology | default=general"
    agent-config: 
      newsapi: 
        api_key: "?"
  - agent-name: "FinancialAnalyst"
    package-name: "FinancialAnalyst"
    capability: "Research the company fundamentals to help analyze company's performance"
    skills:
      - skill-name: "companyProfile"
        objective: "Learn more about a company such as what they do, their HQ location, market capitalization, and who's who"
        action: "companyProfile"
        parameters:
          stock_symbol: "string | Stock Symbol for the specified company, e.g. MSFT for Microsoft"
      - skill-name: "incomeStatement"
        objective: "Obtain the income statement for specified company. It focuses on the revenue, expenses, gains, and losses of a company during a particular period. An income statement provides valuable insights into a company’s operations, the efficiency of its management, underperforming sectors, and its performance relative to industry peers"
        action: "incomeStatement"
        parameters:
          stock_symbol: "string | Stock Symbol for the specified company, e.g. MSFT for Microsoft"
      - skill-name: "balanceSheet"
        objective: "Obtain the balance sheet for specified company. It reports a company's assets, liabilities, and shareholder equity. The balance sheet adheres to an equation where Assets equal sum of Liabilities and Equity. Fundamental analysts use balance sheets to calculate financial ratios"
        action: "balanceSheet"
        parameters:
          stock_symbol: "string | Stock Symbol for the specified company, e.g. MSFT for Microsoft"
      - skill-name: "cashFlowStatement"
        objective: "Obtain the cash flow statement (CFS) for specified company. It not only summarizes the amount of cash and cash equivalents entering and leaving a company, but also highlights how well a company generates cash. The main components of the CFS are cash in and out from three major areas, viz. Operating, Investing, and Financing activities"
        action: "cashFlowStatement"
        parameters:
          stock_symbol: "string | Stock Symbol for the specified company, e.g. MSFT for Microsoft"
      - skill-name: "historicalStockPrices"
        objective: "Analyze stock prices for a valid listed company over past few days"
        action: "historicalStockPrices"
        parameters:
          stock_symbol: "string | Stock Symbol for the specified company, e.g. MSFT for Microsoft"
          number_records: "number | Specify number of records to present. default value = 7"
    agent-config: 
      financialmodelingprep: 
        api_key: "?"
  - agent-name: "Writer"
    package-name: "Writer"
    capability: "Writes aptly drafted communication messages for email, SMS, or social media interactions"
    skills:
      - skill-name: "composeEmail"
        objective: "Write an email message to respond to a specified situation or as a reply to an existing email"
        action: "composeEmail"
        parameters:
          to: "string | To whom the email is addressed"
          situation: "string | Describe the situation for which an email must be written"
          outcome: "string | Describe the outcome that is expected after sending this email"
          original_email: "string | (optional) Provide original email for which a reply must be generated"
      - skill-name: "socialMessage"
        objective: "Write a message suitable for social media messengers, such as LinkedIn, Twitter, etc., or mobile phone text messages, about a specified situation or as a reply to an existing message"
        action: "socialMessage"
        parameters:
          to: "string | To whom the message is addressed"
          situation: "string | Describe the situation for which this message must be written"
          outcome: "string | Describe the outcome that is expected after sending this message"
          original_message: "string | (optional) Provide original message for which a reply must be generated"
    agent-config: {}
  - agent-name: "CineExpert"
    package-name: "CineExpert"
    capability: "An expert on Movies who knows everything from movie details, directors, actors and to some extent user reviews"
    skills:
      - skill-name: "askAnything"
        objective: "ask anything about movie(s), director(s), and actor(s)"
        action: "askAnything"
        parameters:
          question: "string | frame a question that can help generate a Neo4J Cypher query and retrieve information from knowledge graph database"
    agent-config: {} 