const broadAIapiEndpoint = "https://broadaidemo-7yg2a2s6sq-uc.a.run.app";

// ------ ..... ------ ..... ------ ..... ------ 
const go = () => {
  let notes = document.getElementById('notes').value; // Get the value from the textbox
  document.getElementById('plan').innerHTML = "";
  document.getElementById('message').innerHTML = "Working ...";
  document.getElementById('notes').disabled = true;
  document.getElementById('btngo').hidden = true;
  // ...

  document.getElementById('plan').innerHTML = "<p>Generating a plan ...</p>";

  // fetch(broadAIapiEndpoint + "/plan", {
  //   method: "POST",
  //   headers: {
  //     "Content-Type": "application/json",
  //   },
  //   body: JSON.stringify({
  //     "notes": notes
  //   })
  // }).then((response) => response.json())
  //   .then((plan) => {

  //     document.getElementById('plan').innerHTML = "<p>Executing the plan generated by BroadAI ... (" + plan.length + " steps)</p>";

  //     fetch(broadAIapiEndpoint + "/execute", {
  //       method: "POST",
  //       headers: {
  //         "Content-Type": "application/json",
  //       },
  //       body: JSON.stringify({
  //         "plan": plan
  //       })
  //     }).then((response) => response.json())
  //       .then((results) => {

  //         document.getElementById('plan').innerHTML = "<h4>Plan & results:</h4>";
  //         document.getElementById('plan').innerHTML += "<ol>";
  //         results.forEach((step) => {
  //           document.getElementById('plan').innerHTML += "<li>" + step.objective + "</li>";
  //           document.getElementById('plan').innerHTML += "<pre>" + JSON.stringify(step.result) + "</pre>";
  //         });
  //         document.getElementById('plan').innerHTML += "</ol>";
  //         document.getElementById('plan').innerHTML += "</div>";

  //         document.getElementById('message').innerHTML = "Almost done ...";

  //         fetch(broadAIapiEndpoint + "/response", {
  //           method: "POST",
  //           headers: {
  //             "Content-Type": "application/json",
  //           },
  //           body: JSON.stringify({
  //             "results": results,
  //             "notes": notes
  //           })
  //         }).then((response) => response.json())
  //           .then((resp) => {

  //             let message = "<div>";
  //             resp.forEach((elem) => {
  //               message += "<" + elem.html_tag + ">" + elem.text + "</" + elem.html_tag + ">";
  //             });
  //             message += "</div>"
  //             document.getElementById('message').innerHTML = message;

  //             document.getElementById('notes').disabled = false;
  //             document.getElementById('btngo').hidden = false;

  //           }).catch((err) => {
  //             document.getElementById('message').innerHTML = "<p style='color:red;'>Uh! Oh!! Something went wrong with my last step.</p>";
  //             document.getElementById('plan').innerHTML = "<h4 style='color:red;'>ABORTED!</h4>";
  //             document.getElementById('notes').disabled = false;
  //             document.getElementById('btngo').hidden = false;
  //           });

  //       }).catch((err) => {
  //         document.getElementById('plan').innerHTML = "<p style='color:red;'>Plan execution ... FAILED</p>";
  //         document.getElementById('notes').disabled = false;
  //         document.getElementById('btngo').hidden = false;
  //       });

  //   }).catch((err) => {
  //     document.getElementById('plan').innerHTML = "<p style='color:red;'>Plan generation ... FAILED</p>";
  //     document.getElementById('notes').disabled = false;
  //     document.getElementById('btngo').hidden = false;
  //   });

  // };
  fetch(broadAIapiEndpoint + "/ask", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      "notes": notes
    })
  }).then((response) => response.json())
    .then((data) => {
      document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'> <div>";
      document.getElementById('plan').innerHTML += "<h4>Plan generated by BroadAI:</h4>";
      document.getElementById('plan').innerHTML += "<ol>";
      data.plan.forEach((step) => {
        document.getElementById('plan').innerHTML += "<li>" + step.objective + "</li>";
        document.getElementById('plan').innerHTML += "<pre>" + JSON.stringify(step.result) + "</pre>";
      });
      document.getElementById('plan').innerHTML += "</ol>";
      document.getElementById('plan').innerHTML += "</div>";

      let message = "<div>";
      data.response.forEach((elem) => {
        message += "<" + elem.html_tag + ">" + elem.text + "</" + elem.html_tag + ">";
      });
      message += "</div>"
      document.getElementById('message').innerHTML = message;

      document.getElementById('notes').disabled = false;
      document.getElementById('btngo').hidden = false;
    });
}; // go


// ------ ..... ------ ..... ------ ..... ------ 
const randomQ = () => {
  const randomQuestions = [
    // Using Researcher skill
    "I'm planning a trip to Paris and I want to explore some local bakeries. Could you find me a list of bakeries in Paris with high ratings?",

    // Using Aviator skill
    "I'm expecting a friend to arrive at JFK Airport tomorrow. Can you tell me the status of flight DL123 from Los Angeles to JFK?",

    // Using Weatherman skill
    "I'm organizing a beach party in Miami this weekend. What's the weather forecast for Saturday afternoon?",

    // Using FinancialAnalyst skill
    "I'm considering investing in Apple Inc. Can you provide me with their latest income statement?",

    // Using Researcher and Aviator skills
    "I'm traveling to London next month and I want to rent a car. Could you find car rental companies near Heathrow Airport and their contact information?",

    // Using Aviator and Weatherman skills
    "I'm flying from Chicago to Denver tomorrow morning. Can you tell me the expected weather conditions at O'Hare International Airport around my departure time?",

    // Using Weatherman and FinancialAnalyst skills
    "I'm planning a farming project in California. What's the weather forecast for the Central Valley region for the next three months, and how might it impact crop yields?",

    // Using Researcher and FinancialAnalyst skills
    "I'm interested in investing in renewable energy companies. Can you provide me with a list of publicly traded solar energy companies along with their recent stock performances?",

    // Using Aviator, Weatherman, and FinancialAnalyst skills
    "I'm a pilot flying from New York to Los Angeles tomorrow morning. Could you provide the weather forecast for Los Angeles International Airport around my expected arrival time, and also check the stock performance of major airlines?",

    // Using Researcher and Weatherman skills
    "I'm planning a hiking trip to the Swiss Alps next week. Could you find the current snow conditions for popular hiking trails in the region?",

    // Using Aviator and Researcher skills
    "I have a layover in Dubai next week and I want to explore some local attractions. Can you find me a list of tourist spots near Dubai International Airport?",

    // Using Weatherman and Aviator skills
    "I'm a pilot scheduled to land in Tokyo tomorrow night. What's the weather forecast for Narita International Airport during my scheduled landing time?",

    // Using FinancialAnalyst and Aviator skills
    "I'm considering investing in Boeing. Can you provide me with their recent balance sheet and also check if there are any significant delays in their flights?",

    // Using Researcher, Weatherman, and FinancialAnalyst skills
    "I'm planning a ski trip to Aspen next month. Could you find ski resorts in the area, check the current snow conditions, and also provide me with the stock performance of companies in the ski resort industry?",

    // Using Aviator and FinancialAnalyst skills
    "I'm flying to Frankfurt next week for a business meeting. Can you provide me with the flight schedule for flights from London Heathrow to Frankfurt Airport, and also check the stock performance of major airlines operating on that route?",

    // Using Researcher and Aviator skills
    "I'm traveling to Tokyo next month and I'm interested in exploring the local cuisine. Could you find me a list of restaurants near Haneda Airport with good reviews?",

    // Using Weatherman and Researcher skills
    "I'm planning a camping trip to Yellowstone National Park next weekend. What's the weather forecast for the park, and could you also find information on nearby camping grounds?",

    // Using FinancialAnalyst, Aviator, and Researcher skills
    "I'm a frequent traveler and I'm considering investing in companies related to travel and tourism. Can you provide me with a list of major airlines, their recent stock performances, and also find hotel chains with strong financials?",

    // Using Weatherman and Aviator skills
    "I'm flying from Sydney to Auckland next week. Can you provide me with the expected weather conditions at Auckland Airport around my arrival time?",

    // Using Researcher and Weatherman skills
    "I'm planning a road trip through the Canadian Rockies next month. Could you find me information on road conditions and the weather forecast for the route?",

    // Using Aviator and FinancialAnalyst skills
    "I'm considering investing in Delta Air Lines. Can you provide me with their recent cash flow statement and also check if there are any disruptions in their flight schedules?",

    // Using Researcher and FinancialAnalyst skills
    "I'm interested in investing in tech startups. Can you provide me with a list of upcoming tech companies with strong growth potential and their latest financial reports?",

    // Using Aviator and Weatherman skills
    "I'm flying from Singapore to Bangkok tomorrow afternoon. Can you tell me the expected weather conditions at Suvarnabhumi Airport around my arrival time?",

    // Using Researcher, Aviator, and FinancialAnalyst skills
    "I'm planning a trip to Hawaii and I want to stay at a luxury resort. Could you find me a list of high-end resorts near Honolulu International Airport, and also check the stock performance of major hotel chains?",

    // Using Weatherman, FinancialAnalyst, and Aviator skills
    "I'm a pilot flying from Dallas to Houston tomorrow morning. Could you provide the weather forecast for George Bush Intercontinental Airport around my departure time, and also check the stock performance of major oil companies?",

    // Using Researcher, Weatherman, and Aviator skills
    "I'm planning a sailing trip to the Caribbean next month. Could you find me information on sailing conditions and the weather forecast for popular sailing destinations?",

    // Using FinancialAnalyst and Researcher skills
    "I'm interested in investing in the healthcare sector. Can you provide me with a list of pharmaceutical companies with promising pipelines and their recent financial statements?",
  ];
  document.getElementById('notes').value = randomQuestions[(Math.floor(Math.random() * randomQuestions.length))];
}; // randomQ()

