const broadAIapiEndpoint = "https://broadaidemo-7yg2a2s6sq-uc.a.run.app";

// ------ ..... ------ ..... ------ ..... ------ 
const go = () => {
  let notes = document.getElementById('notes').value; // Get the value from the textbox
  document.getElementById('plan').innerHTML = "";
  document.getElementById('message').innerHTML = "Working ...";
  document.getElementById('notes').disabled = true;
  document.getElementById('btngo').hidden = true;
  // ...

  document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
  document.getElementById('plan').innerHTML += "<p>Generating a plan ...</p>";

  fetch(broadAIapiEndpoint + "/plan", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      "notes": notes
    })
  }).then((response) => response.json())
    .then((plan) => {

      document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
      document.getElementById('plan').innerHTML += "<p>Executing the plan generated by BroadAI ... (" + plan.length + " steps)</p>";

      fetch(broadAIapiEndpoint + "/execute", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          "plan": plan
        })
      }).then((response) => response.json())
        .then((results) => {

          document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'> <div>";
          document.getElementById('plan').innerHTML += "<h4>Plan & results:</h4>";
          document.getElementById('plan').innerHTML += "<ol>";
          results.forEach((step) => {
            document.getElementById('plan').innerHTML += "<li>" + step.objective + "</li>";
            document.getElementById('plan').innerHTML += "<pre>" + JSON.stringify(step.result) + "</pre>";
          });
          document.getElementById('plan').innerHTML += "</ol>";
          document.getElementById('plan').innerHTML += "</div>";

          document.getElementById('message').innerHTML = "Almost done ...";

          fetch(broadAIapiEndpoint + "/response", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              "results": results,
              "notes": notes
            })
          }).then((response) => response.json())
            .then((resp) => {

              let message = "<div>";
              resp.forEach((elem) => {
                message += "<" + elem.html_tag + ">" + elem.text + "</" + elem.html_tag + ">";
              });
              message += "</div>"
              document.getElementById('message').innerHTML = message;

              document.getElementById('notes').disabled = false;
              document.getElementById('btngo').hidden = false;

            }).catch((err) => {
              document.getElementById('message').innerHTML = "<p>Uh! Oh!! Something went wrong with my last step.</p>";
              document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
              document.getElementById('plan').innerHTML = "<p>ABORTED!</p>";
            });

        }).catch((err) => {
          document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
          document.getElementById('plan').innerHTML += "<p>Plan execution ... FAILED</p>";
        });

    }).catch((err) => {
      document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
      document.getElementById('plan').innerHTML += "<p>Plan generation ... FAILED</p>";
    });

};
// fetch(broadAIapiEndpoint + "/ask", {
//   method: "POST",
//   headers: {
//     "Content-Type": "application/json",
//   },
//   body: JSON.stringify({
//     "notes": notes
//   })
// }).then((response) => response.json())
//   .then((data) => {
//     document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'> <div>";
//     document.getElementById('plan').innerHTML += "<h4>Plan generated by BroadAI:</h4>";
//     document.getElementById('plan').innerHTML += "<ol>";
//     data.plan.forEach((step) => {
//       document.getElementById('plan').innerHTML += "<li>" + step.objective + "</li>";
//       document.getElementById('plan').innerHTML += "<pre>" + JSON.stringify(step.result) + "</pre>";
//     });
//     document.getElementById('plan').innerHTML += "</ol>";
//     document.getElementById('plan').innerHTML += "</div>";

//     let message = "<div>";
//     data.response.forEach((elem) => {
//       message += "<" + elem.html_tag + ">" + elem.text + "</" + elem.html_tag + ">";
//     });
//     message += "</div>"
//     document.getElementById('message').innerHTML = message;

//     document.getElementById('notes').disabled = false;
//     document.getElementById('btngo').hidden = false;
//   });
// ...
// }; // go


// ------ ..... ------ ..... ------ ..... ------ 
const randomQ = () => {
  const randomQuestions = [
    // Using Researcher skill
    "I'm planning a vacation to Paris next month. Can you find some popular tourist attractions and their opening hours for me?",

    // Using Aviator skill
    "I'm expecting a friend to arrive at JFK Airport tomorrow. Can you check the status of Delta flight 123 from Los Angeles?",

    // Using Weatherman skill
    "I'm hosting a barbecue this weekend. What's the weather forecast for Saturday in Chicago?",

    // Using FinancialAnalyst skill
    "I'm considering investing in Apple (AAPL). Could you provide an overview of their recent financial performance?",

    // Using Researcher and Aviator skills
    "I'm planning a business trip to Tokyo next week. Can you find some reputable hotels near Haneda Airport and their availability for my travel dates?",

    // Using Researcher and Weatherman skills
    "I'm thinking of relocating to Vancouver. Could you gather information about the cost of living there and also provide an overview of the typical weather patterns?",

    // Using Aviator and FinancialAnalyst skills
    "I'm interested in airline stocks. Can you tell me how United Airlines (UAL) performed financially in the last quarter?",

    // Using Aviator and Weatherman skills
    "I have a flight scheduled from London Heathrow to New York JFK next Monday. What's the weather forecast for both cities around the departure and arrival times?",

    // Using Weatherman and FinancialAnalyst skills
    "I'm considering starting a beachside café in Miami. What's the typical weather trend there throughout the year, and how might that impact business revenue?",

    // Using Researcher, Aviator, and FinancialAnalyst skills
    "I'm interested in the hospitality industry. Could you find some data on hotel occupancy rates near Orlando International Airport and also provide insights into recent trends in the hotel industry?",

    // Using Researcher, Weatherman, and FinancialAnalyst skills
    "I'm looking to invest in renewable energy companies. Can you gather information on solar power companies in California, including their financial performance and the typical weather conditions for solar energy generation?",

    // Using all skills
    "I'm planning a ski trip to Aspen next winter. Can you find flights from major airports to Aspen Pitkin County Airport, check their current status, and also provide an overview of Aspen's weather during ski season?",

    // Using all skills
    "I'm considering opening a vineyard in Napa Valley. Could you gather data on the local weather patterns, analyze recent financial reports of successful wineries in the area, and also provide information on inbound flights to the nearest airport?",

    // Using all skills
    "I'm organizing a company retreat in Hawaii. Can you help me find a resort with conference facilities, check flight availability to Honolulu International Airport, and provide a weather forecast for our planned dates?",

    // Using all skills
    "I'm a travel blogger planning my next adventure. Can you help me research popular destinations, check flight options, provide weather forecasts, and analyze the financial feasibility of my travel plans?",

    // Using all skills
    "I'm a consultant advising a client on expanding their retail business. Can you assist me in researching potential locations, checking flight accessibility, analyzing local weather conditions, and assessing the financial viability of the proposed expansion?",
  ];
  document.getElementById('notes').value = randomQuestions[(Math.floor(Math.random() * randomQuestions.length))];
}; // randomQ()

