const broadAIapiEndpoint = "https://broadaidemo-7yg2a2s6sq-uc.a.run.app";

// ------ ..... ------ ..... ------ ..... ------ 
const go = () => {
  let notes = document.getElementById('notes').value; // Get the value from the textbox
  document.getElementById('plan').innerHTML = "";
  document.getElementById('message').innerHTML = "Working ...";
  document.getElementById('notes').disabled = true;
  document.getElementById('btngo').hidden = true;
  // ...

  document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
  document.getElementById('plan').innerHTML += "<p>Generating a plan ...</p>";

  fetch(broadAIapiEndpoint + "/plan", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      "notes": notes
    })
  }).then((response) => response.json())
    .then((plan) => {

      document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
      document.getElementById('plan').innerHTML += "<p>Executing the plan generated by BroadAI ... (" + plan.length + " steps)</p>";

      fetch(broadAIapiEndpoint + "/execute", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          "plan": plan
        })
      }).then((response) => response.json())
        .then((results) => {

          document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'> <div>";
          document.getElementById('plan').innerHTML += "<h4>Plan & results:</h4>";
          document.getElementById('plan').innerHTML += "<ol>";
          results.forEach((step) => {
            document.getElementById('plan').innerHTML += "<li>" + step.objective + "</li>";
            document.getElementById('plan').innerHTML += "<pre>" + JSON.stringify(step.result) + "</pre>";
          });
          document.getElementById('plan').innerHTML += "</ol>";
          document.getElementById('plan').innerHTML += "</div>";

          document.getElementById('message').innerHTML = "Almost done ...";

          fetch(broadAIapiEndpoint + "/response", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              "results": results,
              "notes": notes
            })
          }).then((response) => response.json())
            .then((resp) => {

              let message = "<div>";
              resp.forEach((elem) => {
                message += "<" + elem.html_tag + ">" + elem.text + "</" + elem.html_tag + ">";
              });
              message += "</div>"
              document.getElementById('message').innerHTML = message;

              document.getElementById('notes').disabled = false;
              document.getElementById('btngo').hidden = false;

            }).catch((err) => {
              document.getElementById('message').innerHTML = "<p>Uh! Oh!! Something went wrong with my last step.</p>";
              document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
              document.getElementById('plan').innerHTML = "<p>ABORTED!</p>";
            });

        }).catch((err) => {
          document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
          document.getElementById('plan').innerHTML += "<p>Plan execution ... FAILED</p>";
        });

    }).catch((err) => {
      document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'>";
      document.getElementById('plan').innerHTML += "<p>Plan generation ... FAILED</p>";
    });

};
// fetch(broadAIapiEndpoint + "/ask", {
//   method: "POST",
//   headers: {
//     "Content-Type": "application/json",
//   },
//   body: JSON.stringify({
//     "notes": notes
//   })
// }).then((response) => response.json())
//   .then((data) => {
//     document.getElementById('plan').innerHTML = "<hr style='border:0.5px dotted;'> <div>";
//     document.getElementById('plan').innerHTML += "<h4>Plan generated by BroadAI:</h4>";
//     document.getElementById('plan').innerHTML += "<ol>";
//     data.plan.forEach((step) => {
//       document.getElementById('plan').innerHTML += "<li>" + step.objective + "</li>";
//       document.getElementById('plan').innerHTML += "<pre>" + JSON.stringify(step.result) + "</pre>";
//     });
//     document.getElementById('plan').innerHTML += "</ol>";
//     document.getElementById('plan').innerHTML += "</div>";

//     let message = "<div>";
//     data.response.forEach((elem) => {
//       message += "<" + elem.html_tag + ">" + elem.text + "</" + elem.html_tag + ">";
//     });
//     message += "</div>"
//     document.getElementById('message').innerHTML = message;

//     document.getElementById('notes').disabled = false;
//     document.getElementById('btngo').hidden = false;
//   });
// ...
// }; // go


// ------ ..... ------ ..... ------ ..... ------ 
const randomQ = () => {
  const randomQuestions = [
    // Using Researcher skill
    "As a researcher, I'm interested in investing in the pharmaceutical industry. Can you find businesses of that type with strong financial fundamentals?",

    "I'm planning a vacation and I want to know the top-rated restaurants in Paris. Can you research the best dining spots in the city?",

    "I'm considering buying a new smartphone. Could you find reviews and comparisons of the latest models available on the market?",

    // Using Aviator skill
    "I have a flight to catch tomorrow morning. Can you tell me the departure time and gate number for my flight from JFK to LAX?",

    "My friend is flying in from London today. Can you check the arrival status of the British Airways flight BA103?",

    "I'm expecting a package via air freight. Could you find out if it has arrived at the airport yet?",

    // Using Weatherman skill
    "I'm planning a picnic this weekend. What's the weather forecast for Saturday in Central Park?",

    "I have a business trip next week. Can you tell me what the weather will be like in Tokyo during my stay?",

    "My cousin is planning to go hiking in the mountains. Can you check if there are any weather advisories for that area?",

    // Using FinancialAnalyst skill
    "I'm looking to invest in a tech company. Can you provide me with the income statement and balance sheet of Apple Inc.?",

    "I'm thinking about buying stock in a retail chain. Could you analyze the historical stock prices of Walmart over the past year?",

    "I'm considering starting my own business. Can you research the market trends and potential competitors in the fitness industry?",

    // Using Aviator and Weatherman skills
    "I'm traveling to Chicago tomorrow. Can you tell me if there are any weather-related delays expected for flights into O'Hare International Airport?",

    "My parents are flying in from Florida, but I heard there's a storm in the area. Can you check if their flight will be affected?",

    "I have a layover in Denver next week. What's the weather forecast for the day I'll be there?",

    // Using Researcher and FinancialAnalyst skills
    "I'm interested in renewable energy companies. Can you find businesses in that sector with strong financial performance?",

    "I'm considering investing in a startup. Could you research the company's profile and provide an analysis of its cash flow statement?",

    "I'm thinking about diversifying my investment portfolio. Can you find me companies in the healthcare sector with promising growth prospects?",

    // Using Researcher, Aviator, and Weatherman skills
    "I'm planning a destination wedding in the Caribbean. Can you research the best resorts, as well as check the weather forecast for the wedding date?",

    "I have a business trip to London next month. Can you find the best flights and also provide the weather forecast for my stay?",

    "I'm considering relocating to a new city for work. Could you research the job market, find flights for a visit, and check the weather forecast for next week?",

    // Using Aviator, Weatherman, and FinancialAnalyst skills
    "I'm attending a conference in New York next week. Can you find me a flight, check the weather forecast, and also analyze the hotel expenses to help me budget?",

    "My company is considering expanding internationally. Can you find flights to potential business locations, check the weather conditions, and provide a cost analysis for the expansion?",

    "I'm planning a vacation to a tropical destination. Can you find me affordable flights, check the weather forecast, and also suggest budget-friendly accommodation options?",
  ];

  document.getElementById('notes').value = randomQuestions[(Math.floor(Math.random() * randomQuestions.length))];
}; // randomQ()

